### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by shummo** [Beetle-II/lumi#23]
Can somebody help mi with this problem?
I've got >ERR_INVALID_ARG_TYPE with alarm/light/say, but the lumi/audio/play command work correctly.

```
Sat Oct 30 18:17:04 2021 daemon.info node[4149]: [33m Получен topic= lumi/light/set [0m
Sat Oct 30 18:17:04 2021 daemon.info node[4149]: [37m message = {"state":"ON", "color":{"r":50,"g":50,"b":50}} [0m
Sat Oct 30 18:17:04 2021 daemon.info node[4149]: [37m setLamp. lamp={"state":"ON", "color":{"r":50,"g":50,"b":50}} [0m
Sat Oct 30 18:17:04 2021 daemon.info node[4149]: [31m TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (50)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at Object.writeFileSync (fs.js:1521:5)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at Object.setLamp (/opt/lumi/gateway.js:266:16)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at MqttClient.<anonymous> (/opt/lumi/mqtt_client.js:28:25)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at MqttClient.emit (events.js:400:28)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at MqttClient._handlePublish (/opt/lumi/node_modules/mqtt/lib/client.js:1277:12)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at MqttClient._handlePacket (/opt/lumi/node_modules/mqtt/lib/client.js:410:12)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at work (/opt/lumi/node_modules/mqtt/lib/client.js:321:12)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at Writable.writable._write (/opt/lumi/node_modules/mqtt/lib/client.js:335:5)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at doWrite (/opt/lumi/node_modules/readable-stream/lib/_stream_writable.js:409:139)
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:     at writeOrBuffer (/opt/lumi/node_modules/readable-stream/lib/_stream_writable.js:398:5) {
Sat Oct 30 18:17:04 2021 daemon.info node[4149]:   code: 'ERR_INVALID_ARG_TYPE'
Sat Oct 30 18:17:04 2021 daemon.info node[4149]: } [0m
```

**Comment by romasu69** [comment]
Hi! I have made the following changes to the gateway.js:

//-----------------------------------
if (state === 'OFF') {
            //fs.writeFileSync(lamp.path.r, 0);
            //fs.writeFileSync(lamp.path.g, 0);
            //fs.writeFileSync(lamp.path.b, 0);
        
           fs.writeFileSync(lamp.path.r, "0");
           fs.writeFileSync(lamp.path.g, "0");
           fs.writeFileSync(lamp.path.b, "0");
}

 if (state === 'ON') {
            if (msg.color) {
                lamp.value.color.r = msg.color.r;
                lamp.value.color.g = msg.color.g;
                lamp.value.color.b = msg.color.b;
            }
            if (msg.brightness) {
                lamp.value.brightness = Math.round(0.2126 * lamp.value.color.r + 0.7152 * lamp.value.color.g + 0.0722 * lamp.value.color.b);

                let k = (msg.brightness / lamp.value.brightness);
                lamp.value.color.r = Math.round(k * lamp.value.color.r);
                lamp.value.color.g = Math.round(k * lamp.value.color.g);
                lamp.value.color.b = Math.round(k * lamp.value.color.b);
            }
            //fs.writeFileSync(lamp.path.r, lamp.value.color.r);
            //fs.writeFileSync(lamp.path.g, lamp.value.color.g);
            //fs.writeFileSync(lamp.path.b, lamp.value.color.b);
            
            fs.writeFileSync(lamp.path.r, lamp.value.color.r.toString());
            fs.writeFileSync(lamp.path.g, lamp.value.color.g.toString());
            fs.writeFileSync(lamp.path.b, lamp.value.color.b.toString());
            
            if (msg.timeout) {
                setTimeout(() => {
                    setLamp('{"state":"OFF"}');
                }, msg.timeout * 1000);
            }
        }
//----------------------------------

Now everything works.

**Comment by shummo** [comment]
Thanks. The lights now working.

Unfortunatelly TTS still not working.
```
ri Dec 17 14:32:01 2021 daemon.info node[6327]:  [37m message = {"text": "Hello"}  [0m
Fri Dec 17 14:32:01 2021 daemon.err node[6327]: /bin/sh: mpg123: not found
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:  [31m Error: Command failed: mpg123 /tmp/8b1a9953c4611296a827abf8c47804d7.mp3
Fri Dec 17 14:32:01 2021 daemon.info node[6327]: /bin/sh: mpg123: not found
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at checkExecSyncError (child_process.js:790:11)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Object.execSync (child_process.js:863:15)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at sayText (/opt/lumi/gateway.js:469:16)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Object.setSay (/opt/lumi/gateway.js:375:13)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient.<anonymous> (/opt/lumi/mqtt_client.js:44:25)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient.emit (events.js:400:28)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient._handlePublish (/opt/lumi/node_modules/mqtt/lib/client.js:1277:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient._handlePacket (/opt/lumi/node_modules/mqtt/lib/client.js:410:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at work (/opt/lumi/node_modules/mqtt/lib/client.js:321:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Writable.writable._write (/opt/lumi/node_modules/mqtt/lib/client.js:335:5) {
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   status: 127,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   signal: null,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   output: [
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     null,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     <Buffer >,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     <Buffer 2f 62 69 6e 2f 73 68 3a 20 6d 70 67 31 32 33 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   ],
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   pid: 9762,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   stdout: <Buffer >,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 6d 70 67 31 32 33 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Fri Dec 17 14:32:01 2021 daemon.info node[6327]: }  [0m
Fri Dec 17 14:32:01 2021 daemon.err node[6327]: /bin/sh: mpg123: not found
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:  [31m Error: Command failed: mpg123 /tmp/602bdcebe181fdd835e044b9bfb57777.mp3
Fri Dec 17 14:32:01 2021 daemon.info node[6327]: /bin/sh: mpg123: not found
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at checkExecSyncError (child_process.js:790:11)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Object.execSync (child_process.js:863:15)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at sayText (/opt/lumi/gateway.js:469:16)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Object.setSay (/opt/lumi/gateway.js:390:9)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient.<anonymous> (/opt/lumi/mqtt_client.js:44:25)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient.emit (events.js:400:28)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient._handlePublish (/opt/lumi/node_modules/mqtt/lib/client.js:1277:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at MqttClient._handlePacket (/opt/lumi/node_modules/mqtt/lib/client.js:410:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at work (/opt/lumi/node_modules/mqtt/lib/client.js:321:12)
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     at Writable.writable._write (/opt/lumi/node_modules/mqtt/lib/client.js:335:5) {
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   status: 127,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   signal: null,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   output: [
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     null,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     <Buffer >,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:     <Buffer 2f 62 69 6e 2f 73 68 3a 20 6d 70 67 31 32 33 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   ],
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   pid: 9763,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   stdout: <Buffer >,
Fri Dec 17 14:32:01 2021 daemon.info node[6327]:   stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 6d 70 67 31 32 33 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>
Fri Dec 17 14:32:01 2021 daemon.info node[6327]: }  [0m
```

**Comment by Beetle-II** [comment]
opkg install mpg123

lamp fixed in last release
